# Having channel errors
name: fastapi-boilerplate
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - fastapi
  - alembic
  - uvicorn
  - sqlalchemy
  - pydantic
  - psycopg2-binary
  - python-multipart
  - requests
  - python-dotenv